### ISSUE TITLE
Check and merge into master

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-instructor-app#3]
Components have been reorganized with additional authoring functionality to support the workflow of: choosing a directive >> choosing question(s) that address that directive >> specifying the number required. Please help merging reorg-components into master? Things to note:
- Tap on a directive to check out EditDirective.js
- Comments littered throughout where stubs are. Feel free to delete when done plugging in.

**Comment by coleshaw** [comment]
merged in 9a079918ef09908a0a4344d2df84a5851b765a31
